IF
  Global("WIQuayDDMachine","ID6011",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Quayle")
  InMyArea("Quayle") 
  !StateCheck("Quayle",STATE_SLEEPING)
THEN
  RESPONSE #100
    SetGlobal("WIQuayDDMachine","ID6011",1)
	DisplayString("Quayle",~Interesting... very interesting. These dwarves must have had a gnome or two in charge, there's no way they would be smart enough to make something like this themselves.~)
END