IF
  Global("WISafaTempForGod","ID3603",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Safana")
  InMyArea("Safana")  
  !StateCheck("Safana",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("WISafaTempForGod","ID3603",1)
	DisplayString("Safana",@1050 /* Remember when looking for this dumb gem stopped being funny? Dear, if we go to another exotic location only to find it isn’t there either, I’m going to give someone a sensual massage around the neck. */)
END
