IF
  Global("HexxJackClanCave","ID9800",0)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  InParty("Hexxat")
  InMyArea("Hexxat")
  !StateCheck("Hexxat",STATE_SLEEPING)
THEN
  RESPONSE #100
    SetGlobal("HexxJackClanCave","ID9800",1)
	DisplayString("Hexxat",@2750 /* I can see the workings of traps up ahead spaced only steps after the last. Move slowly unless you wish for a quick death. */)
END